# Generated by Django 3.0.1 on 2019-12-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='forum.Basket'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='forum.Book'),
        ),
    ]
